const constants = {
  SET_GOAL: 'SET_GOAL',

  FETCH_TERMS: 'FETCH_TERMS',
  ADD_TERM: 'ADD_TERM',
  REMOVE_TERM: 'REMOVE_TERM',

  ADD_MESSAGE: 'ADD_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',

  CANCEL_FETCHING: 'CANCEL_FETCHING',
  CHANGE_SUGGESTIONS: 'CHANGE_SUGGESTIONS',
  CLEAR_SUGGESTIONS: 'CLEAR_SUGGESTIONS'
}

export default constants
