const constants = {
  SORT_TYPE_ASC: 'ASC',
  SORT_TYPE_DESC: 'DESC',

  SET_TIMEZONE: 'SET_TIMEZONE',
  STATES: 'STATES',
  INIT_COUNTRIES: 'INIT_COUNTRIES',
  INIT_LANGUAGES: 'INIT_LANGUAGES',
  GET_AWARD_TYPE_BY_VALUE: 'GET_AWARD_TYPE_BY_VALUE',
  GET_AWARD_TYPES_BY_VALUES: 'GET_AWARD_TYPES_BY_VALUES',
  GET_EDU_GOAL_BY_VALUE: 'GET_EDU_GOAL_BY_VALUE',
  GET_EDU_GOALS_BY_VALUES: 'GET_EDU_GOALS_BY_VALUES',

  INIT_USER: 'INIT_USER',
  CHANGE_USER_ROLE: 'CHANGE_USER_ROLE',

  DT_COLUMN_RESIZE: 'DT_COLUMN_RESIZE',

  FETCH_TERMS: 'FETCH_TERMS',
  UPDATE_TERMS_SEARCH_RESULTS: 'UPDATE_TERMS_SEARCH_RESULTS',
  ADD_TERM: 'ADD_TERM',
  ARCHIVE_TERM: 'ARCHIVE_TERM',
  TERMS_SET_COLLEGE: 'TERMS_SET_COLLEGE',

  FETCH_DISTRICTS: 'FETCH_DISTRICTS',
  UPDATE_DISTRICTS_POPULATION: 'UPDATE_DISTRICTS_POPULATION',
  DISTRICTS_SORT_CHANGE: 'DISTRICTS_SORT_CHANGE',

  SET_COLLEGE: 'SET_COLLEGE',
  FETCH_COLLEGES: 'FETCH_COLLEGES',
  UPDATE_COLLEGES_POPULATION: 'UPDATE_COLLEGES_POPULATION',
  COLLEGES_SORT_CHANGE: 'COLLEGES_SORT_CHANGE',

  ADD_MESSAGE: 'ADD_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',

  CANCEL_FETCHING: 'CANCEL_FETCHING',
  CHANGE_SUGGESTIONS: 'CHANGE_SUGGESTIONS',
  CLEAR_SUGGESTIONS: 'CLEAR_SUGGESTIONS',
  CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS'
}

export default constants
